//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meiday.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Meiday.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   • 개인(신용)정보의 수집 · 이용 목적
        ///   - 보험금지급 ·심사(보험금청구서류 접수대행 서비스 포함, 잔존물 대위, 구상업무 관련) 및 보험사고 조사(보험사기 조사 포함),
        /// 보험금지급관련 민원처리 및 분쟁대응
        ///   - 금융거래(보험료 및 보험금 등 출·수납을 위한 금융거래 신청, 자동이체 등 접수) 관련업무
        ///
        ///• 수집 · 이용할 개인(신용)정보의 내용
        ///   - 개인식별정보(성명, 주민등록번호, 외국인등록번호, 운전면허증번호, 주소, 전화번호, 전자우편주소, 가족관계서류,
        /// 주민번호(초)등본, 계좌정보 등)
        ///   - 보험사고 조사(보험사기 조사 포함)및 손해사정업무 수행과 관련하여 취득한 개인 (신용)정보[검·경 등 수사기관,공공기관,
        /// 의료기관 등으로부터 본인의 위임을 받아 취득한 각종 조사서,증명서,진료기록 등에 포함된 개인(신용)정보 포함]
        ///
        ///• 개인(신용)정보의 보유 · 이용 기간
        ///   - 수집·이용 동의일로부터 거래종료 후 5년까지(단, 거래종료 후 5년이 경과한 후에는[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Insu01Detailed01 {
            get {
                return ResourceManager.GetString("Insu01Detailed01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   • 개인(신용)정보 조회목적
        ///  - 보험금지급·심사(보험금청구서류 접수대행 서비스 포함) 및 보험사고 조사(보험사기 조사 포함)
        ///
        ///• 조회할 개인(신용)정보
        ///   - 보험계약정보, 보험금지급 관련 정보(사고정보 포함), 질병 및 상해 관련 정보, 운전면허정보, 무면허 운전 여부 및 음주운전
        /// 여부 정보 조회(보험금 지급 및 사고정보는 과거 및 현재의 당사 자동차보험 처리 내용을 포함함)
        /// ※ 보험요율산출기관으로부터의 조회는 보험개발원의 보험사고정보 시스템(ICPS)을 통한 개인(신용)정보 조회를 말합니다.
        ///
        ///• 조회동의 유효기간 및 조회자(개인(신용)정보를 제공받는 자)의 개인(신용)정보 보유 · 이용 기간
        ///   - 수집·이용 동의일로부터 거래종료 후 5년까지(단, 거래종료 후 5년이 경과한 후에는 보험금 지급, 금융사고 조사, 분쟁해결,
        /// 민원처리, 법령상 의무이행을 위한 경우에 한하여 보유·이용하며, 별도 보관함)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Insu01Detailed02 {
            get {
                return ResourceManager.GetString("Insu01Detailed02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   • 개인(신용)정보를 제공받는 자(제3자)
        ///   - 신용정보집중기관 : 생명보험협회, 손해보험협회 등 신용정보집중기관
        /// - 공공기관 등 : 금융위원회, 국토해양부, 금융감독원, 보험요율산출기관 등 공공기관, 법원, 검찰, 국세청, 경찰청 등 법령상
        /// 업무 수행기관(위탁사업자 포함) 등
        ///   - 보험회사 등 : 생명보험사, 손해보험사, 국내·국외 재보험사, 공제사업자, 체신관서(우체국보험), 금융거래 관련 계좌개설
        /// 금융기관, 금융결제원 등
        ///   - 업무수탁자 등 : 보험금지급 ·심사 및 보험사고조사 등에 필요한 업무를 위탁받은 자[삼성화재 자회사, 위탁콜센터 및 간이심사제에
        /// 따라 삼성화재로부터 지급심사 및 사고조사를 위탁받은 협력법인·보험사고 조사업체·손해사정업체, 의료기관(의사), 법무법인(변
        /// 호사), 추심업체, 잔존물 매각업체], 손해보험협회, 건강보험심사평가원, 청구 계약의 보험모집인(보험설계사·보험대리점 등) 등
        ///
        ///• 개인(신용)정보를 제공받는 자의 이용목적
        ///   - 신용정[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Insu01Detailed03 {
            get {
                return ResourceManager.GetString("Insu01Detailed03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap logo33 {
            get {
                object obj = ResourceManager.GetObject("logo33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap MEIDAY {
            get {
                object obj = ResourceManager.GetObject("MEIDAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   fasdffadsfasdf과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
